### ISSUE TITLE
Delorean support for timedelta arithmetic 

### ISSUE THREAD

**Issue by fawce** [myusuf3/delorean#23]
The timedelta class in the datetime package is very useful for calendar/time arithmetic. It would be great if Deloreans had the same behavior as datetime objects:

```
from datetime import timedelta, datetime
from delorean import Delorean

dd1 = Delorean(datetime(2013, 2, 15), "US/Eastern")
dd2 = Delorean(datetime(2013, 2, 16), "US/Eastern")

one_day = dd2 - dd1
assert one_day == timedelta(days=1)
assert (dd1 + one_day) == dd2
```

**Comment by myusuf3** [comment]
This has been merged in and released in the latest 0.5.0 Release.

http://delorean.readthedocs.org/en/latest/quickstart.html#time-arithmetic
