### ISSUE TITLE
epoch issue?

### ISSUE THREAD

**Issue by eddwardo** [myusuf3/delorean#31]
In [57]: Delorean(datetime.now(), timezone='UTC').epoch() - time.time()
Out[57]: 7199.999927997589

In [58]: time.mktime(Delorean(datetime.now(), timezone='UTC').datetime.timetuple()) - time.time()
Out[58]: 3599.633516073227

**Comment by mlew** [comment]
This issue is invalid.  `datetime.timetuple()` returns a localized timetuple.  Try the following, substituting your local timezone for 'US/Pacific'.

```python
>>> d = Delorean(datetime(2015, 1, 1), timezone='US/Pacific')
>>> d.epoch()
1420099200.0
>> time.mktime(d.datetime.timetuple())
1420099200.0
```

**Comment by eddwardo** [comment]
Thanks!

**Comment by myusuf3** [comment]
That in a nutshell is why I dislike datetime. :100: Thanks for the quick response there @mlew
