### ISSUE TITLE
Cut a release with arithmetic fixes?

### ISSUE THREAD

**Issue by josefdlange** [myusuf3/delorean#57]
I'm curious if you could make a PyPI version update with those changes from a couple weeks (months?) ago. It would be quite beneficial to me...

**Comment by myusuf3** [comment]
Doing it now!

**Comment by myusuf3** [comment]
https://pypi.python.org/pypi/Delorean/0.5.0

**Comment by myusuf3** [comment]
I was holding off to cut a 1.0 Release.
