### ISSUE TITLE
__eq__ should return True for datetimes that are UTC equal

### ISSUE THREAD

**Issue by mlew** [myusuf3/delorean#61]
Delorean should know if two times are UTC equal.  The following code will return False:

```python
>>> d1 = Delorean(datetime(2015, 1, 1), timezone='US/Pacific')
>>> d2 = Delorean(datetime(2015, 1, 1, 8), timezone='UTC')
>>> d1 == d2
False
```

The two times are actually equivalent, so it seems like the above code should return True.  Maybe this is working as intended, but I was unable to find any documentation supporting that decision.

**Comment by myusuf3** [comment]
Will close issue once corresponding documentation comes in. :+1:
