### ISSUE TITLE
Your datetime readme example is broken

### ISSUE THREAD

**Issue by pmaupin** [myusuf3/delorean#70]
as discussed here:

http://stackoverflow.com/questions/31886808/when-does-datetime-nowpytz-timezone-fail

Effective code:

    d = datetime.utcnow()
    utc = timezone(UTC)
    est = timezone(EST)
    d = utc.localize(d)
    d = est.normalize(EST)
    return d

becomes:

    est = timezone(EST)
    d = est.normalize(EST)
    return d

becomes:

    return timezone(EST).normalize(EST)

**Comment by mlew** [comment]
Thanks for catching @pmaupin.  Here's a pull request to fix it.

**Comment by myusuf3** [comment]
Thanks @miew
