### ISSUE TITLE
Fix midnight() and naive() references on Quickstart page

### ISSUE THREAD

**Issue by agosto-krishokanson** [myusuf3/delorean#88]
The [overview](http://delorean.readthedocs.org/en/latest/) mentions that 

- _Delorean.epoch_ is a property, not a function.
- _Delorean.midnight_ is a property, not a function.
- _Delorean.naive_ is a property, not a function.
- _Delorean.timezone_ is a property, not a function.

but the [quickstart page](http://delorean.readthedocs.org/en/latest/quickstart.html) still has examples showing `midnight()` and `naive()`

**Comment by myusuf3** [comment]
Thanks for bringing this to my attention!

I wont have a chance to address this soon, but if you submit a PR. I will see it merged in.

**Comment by agosto-krishokanson** [comment]
Wow, thanks for fixing this so quickly, guys!  I was going to submit a PR but you beat me to it before I had time!
