### ISSUE TITLE
Delorean.shift does not take datetime.timezone.utc

### ISSUE THREAD

**Issue by numberoverzero** [myusuf3/delorean#97]
To reproduce:

```python
import delorean
import datetime

utc = datetime.timezone.utc
dt = datetime.datetime(2017, 3, 5, 3, 1, 46, 425154, tzinfo=utc)

d = delorean.Delorean(dt).shift(utc)
```

[From these lines](https://github.com/myusuf3/delorean/blob/10cc1ed91619cb529efae0ed2e9679f90303c90f/delorean/dates.py#L483-L486), Delorean doesn't support anything outside of `pytz.timezone` ability to parse, which breaks on `zone.upper()` [at the beginning of this method](https://github.com/stub42/pytz/blob/7b5e9dc015252d3650ec086118b20fedacef0def/src/pytz/__init__.py#L126-L165).

Should I always use `"UTC"` instead of datetime's provided `datetime.timezone.utc`?  I was hoping to reuse the standard library's version across different datetime libraries.

**Comment by jacobKKK** [comment]
Is convert `datetime.timezone` and `pytz.timezone` in `Delorean( ).shift( )` a good solution to these problem?

**Comment by myusuf3** [comment]
You should always use `UTC` why would you pull in datetime to just ask for `utc` timezone. There are few examples that cover what you are trying to do at http://delorean.rtfd.org.

**Comment by numberoverzero** [comment]
Thanks for the response.  I'm pulling in datetime for more than utc but wanted to provide a minimal example.  I'll use `"UTC"` instead.

I was hoping that `.shift` would handle a `datetime.tzinfo` instance (as well as a string through the use of `pytz`) because I provide a library that maps dynamodb objects to python types, and I include [an extension for Delorean](https://github.com/numberoverzero/bloop/blob/d892751adfd1357fc879e17548d00989d5af3866/bloop/ext/delorean.py#L27) which simply forwards the users' `timezone` parameter through.

I expect most users will provide a string such as "utc" and things will be fine, but some may use a custom `datetime.tzinfo` subclass; `datetime.timezone` is simply a concrete example of the problem.  [From the docs](https://docs.python.org/3/library/datetime.html#timezone-objects):

>  Note that only one concrete tzinfo class, the timezone class, is supplied by the datetime module. The timezone class can represent simple timezones with fixed offset from UTC, such as UTC itself or North American EST and EDT timezones.
